// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * String is a nullable string. It supports SQL and JSON serialization.
 * It will marshal to null if null. Blank string input will be considered null.
 * @typedef {$models.String} String
 */

/**
 * Time is a nullable time.Time. It supports SQL and JSON serialization.
 * It will marshal to null if null.
 * @typedef {$models.Time} Time
 */
