// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * String is a nullable string. It supports SQL and JSON serialization.
 * It will marshal to null if null. Blank string input will be considered null.
 * @typedef {any} String
 */

/**
 * Time is a nullable time.Time. It supports SQL and JSON serialization.
 * It will marshal to null if null.
 * @typedef {any} Time
 */
