version: '3'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

vars:
  APP_NAME: "MQTT Viewer"
  BIN_DIR: "build/bin"

tasks:
  build:
    summary: Builds the application
    cmds:
    - task: "{{OS}}:build"

  run:
    summary: Runs the application
    cmds:
    - task: "{{OS}}:run"
